name: SuperPets
author: RTGTeam
description: A small pets plugin, lol
version: 2.0.0 
main: pets\main
api: [2.0.0] 
commands:
 pets:
  description: "Pets"
  usage: "/pets"
  permission: superpets.master
permissions:
  superpets.master:
    description: "Allows RP toggle on/off"
    default: true