name: SuperPets
author: RTGTeam
description: Regeneration for IG!
version: 3.0.7
main: pets\main
api: [1.13.0, 1.14.0, 2.0.0]
permissions:
  superpets.cmd:
    default: op
  superpets.ca:
    default: op
  superpets.tag:
    default: op
